[tool.bumpversion]
current_version = "26.4.23"
commit = true
tag = true
tag_name = "v{new_version}"
tag_message = "release: v{new_version}"
commit_message = "release: v{new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.dev(?P<dev>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}.dev{dev}",
    "{major}.{minor}.{patch}",
]

[tool.bumpversion.parts.dev]
optional_value = ""
first_value = "0"

[[tool.bumpversion.files]]
filename = "version.typ"
search = '#let version = "{current_version}"'
replace = '#let version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "typst.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
